drop table json_extract11;

CREATE TABLE json_extract11(
uniqueVisitID varchar(100),
visitID varchar(100),
fullVisitorId varchar(100),
userid varchar(100),
visitstarttime varchar(100),
visitnumber varchar(100),
date varchar(100),
hitnumber varchar(100),
hit_time varchar(20),
hit_hour varchar(10),
hit_minute varchar(10),
hit_isEntrance boolean,
hit_isExit boolean,
hit_isInteraction boolean,
latitude varchar(10),
longitude varchar(10),
pagepath text,
pagetitle text,
screenresolution varchar(10),
mobileDeviceInfo varchar(50),
deviceCategory varchar(10),
language varchar(10),
campaign varchar(100),
keyword varchar(100),
medium varchar(10),
referral_path text,
source varchar(50),
bounces text );